export const artistsList: string[] = [
  "Imagine Dragons",
  "Eminem",
  "Paul McCartney",
  "Elton John",
  "Taylor Swift",
  "ABBA",
  "BTS",
  "Hozier",
  "Gracie Abrams",
  "Katy Perry",
  "Lana Del Rey",
  "Olivia Rodrigo",
  "Dr.Dre",
  "YungBlud",
  "2 Chainz",
  "Lil wayne",
  "James Arthur",
  "Post Malone",
  "Zayn",
  "Niall Horran",
];
